version: 2.1
jobs:
  test-build-deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit & Integration test
          command: npm test
      - run:
          name: Build & Archive
          command: source ./archive.sh
      - run:
          name: CDK Deploy to AWS
          command: source ./deploy.sh
          
workflows:
  test-build-deploy:
    jobs:
      - test-build-deploy