version: 2.1
jobs:
  test-build-deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: source ./archive.sh && echo $BUNDLE_NAME > /tmp/bundle-name
      - run: export $BUNDLE_NAME=`cat /tmp/bundle-name` && source ./deploy

workflows:
  test-build-deploy:
    jobs:
      - test-build-deploy