version: 2.1
jobs:
  test-build-deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit & Integration test
          command: npm test
      - run:
          name: Install AWS CDK deploy deps
          command: sudo npm install -g typescript ts-node aws-cdk
      - run:
          name: Build & Archive
          command: source ./archive.sh && echo $BUNDLE_NAME > /tmp/bundle-name
      - run:
          name: CDK Deploy to AWS
          command: BUNDLE_NAME=`cat /tmp/bundle-name` source ./deploy.sh

workflows:
  test-build-deploy:
    jobs:
      - test-build-deploy