version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: . ./archive.sh && echo $BUNDLE_NAME > /tmp/bundle-name